export const CATEGORY_EMOJIS = {
  bed_bath_table: "🛏️",
  health_beauty: "💄",
  sports_leisure: "⚽",
  furniture_decor: "🪑",
  computers_accessories: "💻",
  watches_gifts: "⌚",
  housewares: "🏠",
  garden_tools: "🌱",
  toys: "🧸",
  baby: "👶",
  cool_stuff: "✨",
  perfumery: "🌸",
  telephony: "📱",
  electronics: "🔌",
  fashion_bags_accessories: "👜",
  books_general_interest: "📚",
  music: "🎵",
  auto: "🚗",
  pet_shop: "🐾",
  office_furniture: "🖥️",
};

export const MOCK_PRODUCTS = [
  {
    id: "prod_001",
    name: "Luxury Bath Towel Set",
    category: "bed_bath_table",
    price: 189.9,
    emoji: "🛏️",
    description: "Ultra-soft cotton towels for a spa-like bathroom feel.",
    rating: 4.8,
    reviews: 412,
  },
  {
    id: "prod_002",
    name: "Hydrating Beauty Kit",
    category: "health_beauty",
    price: 249.9,
    emoji: "💄",
    description: "Complete skincare routine with Brazilian botanical extracts.",
    rating: 4.6,
    reviews: 287,
  },
  {
    id: "prod_003",
    name: "Weekend Fitness Bundle",
    category: "sports_leisure",
    price: 159.9,
    emoji: "⚽",
    description: "Lightweight gear set for workouts and outdoor runs.",
    rating: 4.4,
    reviews: 198,
  },
  {
    id: "prod_004",
    name: "Modern Accent Chair",
    category: "furniture_decor",
    price: 699.9,
    emoji: "🪑",
    description: "Contemporary chair with premium fabric and wooden legs.",
    rating: 4.7,
    reviews: 64,
  },
  {
    id: "prod_005",
    name: "Wireless Office Bundle",
    category: "computers_accessories",
    price: 329.9,
    emoji: "💻",
    description: "Keyboard, mouse, and stand for a tidy workspace.",
    rating: 4.5,
    reviews: 305,
  },
  {
    id: "prod_006",
    name: "Premium Watch Gift Box",
    category: "watches_gifts",
    price: 499.9,
    emoji: "⌚",
    description: "Elegant timepiece set with leather strap and case.",
    rating: 4.6,
    reviews: 143,
  },
  {
    id: "prod_007",
    name: "Smart Kitchen Starter",
    category: "housewares",
    price: 219.9,
    emoji: "🏠",
    description: "Stylish kitchen utensils and storage essentials.",
    rating: 4.3,
    reviews: 92,
  },
  {
    id: "prod_008",
    name: "Garden Care Toolkit",
    category: "garden_tools",
    price: 149.9,
    emoji: "🌱",
    description: "Compact toolset for balconies and urban gardens.",
    rating: 4.2,
    reviews: 58,
  },
  {
    id: "prod_009",
    name: "Wooden Toy Collection",
    category: "toys",
    price: 139.9,
    emoji: "🧸",
    description: "Safe, colorful toys crafted from sustainable wood.",
    rating: 4.9,
    reviews: 320,
  },
  {
    id: "prod_010",
    name: "Baby Comfort Starter",
    category: "baby",
    price: 199.9,
    emoji: "👶",
    description: "Soft blanket, pillow, and essentials for newborns.",
    rating: 4.7,
    reviews: 141,
  },
  {
    id: "prod_011",
    name: "Creative Cool Desk Set",
    category: "cool_stuff",
    price: 129.9,
    emoji: "✨",
    description: "Organizers and gadgets for a stylish desk vibe.",
    rating: 4.4,
    reviews: 76,
  },
  {
    id: "prod_012",
    name: "Floral Perfume Duo",
    category: "perfumery",
    price: 299.9,
    emoji: "🌸",
    description: "Signature scents inspired by Brazilian gardens.",
    rating: 4.8,
    reviews: 215,
  },
  {
    id: "prod_013",
    name: "Smartphone Essentials Pack",
    category: "telephony",
    price: 99.9,
    emoji: "📱",
    description: "Fast charger, case, and screen protector bundle.",
    rating: 4.2,
    reviews: 368,
  },
  {
    id: "prod_014",
    name: "Home Electronics Hub",
    category: "electronics",
    price: 799.9,
    emoji: "🔌",
    description: "Compact smart speaker with voice control.",
    rating: 4.6,
    reviews: 246,
  },
  {
    id: "prod_015",
    name: "City Bag Organizer",
    category: "fashion_bags_accessories",
    price: 89.9,
    emoji: "👜",
    description: "Lightweight organizer for handbags and totes.",
    rating: 4.1,
    reviews: 57,
  },
  {
    id: "prod_016",
    name: "Classic Literature Bundle",
    category: "books_general_interest",
    price: 119.9,
    emoji: "📚",
    description: "Curated Brazilian classics for cozy evenings.",
    rating: 4.8,
    reviews: 401,
  },
  {
    id: "prod_017",
    name: "Vinyl Listening Set",
    category: "music",
    price: 349.9,
    emoji: "🎵",
    description: "Portable player with iconic Brazilian records.",
    rating: 4.5,
    reviews: 88,
  },
  {
    id: "prod_018",
    name: "Car Care Premium Kit",
    category: "auto",
    price: 159.9,
    emoji: "🚗",
    description: "Detailing essentials for showroom shine.",
    rating: 4.3,
    reviews: 63,
  },
  {
    id: "prod_019",
    name: "Pet Comfort Lounge",
    category: "pet_shop",
    price: 189.9,
    emoji: "🐾",
    description: "Soft bed and grooming kit for your pet.",
    rating: 4.7,
    reviews: 120,
  },
  {
    id: "prod_020",
    name: "Executive Office Desk",
    category: "office_furniture",
    price: 899.9,
    emoji: "🖥️",
    description: "Spacious desk with cable management and drawers.",
    rating: 4.6,
    reviews: 39,
  },
];
